spring:
  server:
    tomcat:
      accept-count: 500
      threads:
        min-spare: 500
        max: 1000
      max-connections: 25000
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    session:
      timeout: 3600
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:openrun"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: ${IMAGE_BUCKET}
      resize-bucket: ${RESIZE_BUCKET}
    stack:
      auto: false
    region:
      static: ap-northeast-2


---
spring:
  redis:
    host: 127.0.01
    port: 6379
    cache:
      type: redis
  server:
    tomcat:
      accept-count: 500
      threads:
        min-spare: 500
        max: 1000
      max-connections: 25000
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    session:
      timeout: 3600
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:mysql://localhost:3306/openrun"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          show_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: ${IMAGE_BUCKET}
      resize-bucket: ${RESIZE_BUCKET}
    stack:
      auto: false
    region:
      static: ap-northeast-2


---
spring:
  config:
    activate:
      on-profile: prod