name: CI-CD

on:
  push:
    branches:
      - CICD

env:
  BUCKET_NAME: codedeploy-asap
  DEPLOY_APPLICATION_NAME: asap-deploy
  DEPLOY_GROUP_NAME: deploy-group

jobs:
  build:
    runs-on: ununtu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-jave@1
        with:
          java-version: 17

      - name: Grant excute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA .
        shell: bash

      - name: Configuration AWS credentals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to s3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$GITHUB_SHA.zip
        
      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.DEPLOY_GROUP_NAME }} \
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
      
